### PR TITLE
Date type 

### LINKED ISSUE #37: Date
Enable parsing and recognition of dates

### PR DESCRIPTION
**Pull request by scottcalebc**
Add functionality for date type conversion that match the exact patter "YYYY-MM-DD". Add builtin functions (all functions accept Date or coerced strings as parameters) will close #37 

 - dateDiff
    - returns number of days between two date types (accounts for leap years)
 - dateAdj
    - returns a date adjusted by some number of days given as a parameter
 - dateAge
    - returns the number of years passed between two dates

 All p4 text files produce correct output and working p5Date output
```
p5Date.txt 
Date 1 str: 736726; Date 2 str: 735995
date1 = 2017-04-01 date2 = 2015-04-01 diff = 731 
date = 2017-04-01 adjusted by 1 = 2017-04-02 
date = 2017-04-01 adjusted by -40 = 2017-02-20 
date = 2017-04-01 adjusted by -365 = 2016-04-01 
date = 2017-04-01 adjusted by -731 = 2015-04-01 
date1 = 2017-02-01 date2 = 2015-02-01 age = 2 
date1 = 2017-02-01 date2 = 1957-12-04 age = 59 
date1 = 2017-02-01 date2 = 1953-12-12 age = 63 

Process finished with exit code 0
```

### CODE REVIEW

**Review by LukeCD12 — COMMENTED** [review]
All looks good besides the fact that we have changed the format for builtin functions. So if you still want the builtins like in feature/BuiltinUpdates. SymbolTable.java will need  small update using Builtin interface

**Comment by scottcalebc** [comment]
> All looks good besides the fact that we have changed the format for builtin functions. So if you still want the builtins like in feature/BuiltinUpdates. SymbolTable.java will need  small update using Builtin interface

Yes yes, but I'm not going to cater a branch to a feature that's not even finished yet. The built in branch will change all the functionality needed regarding built in's this branch is just implementing dates based on the current standards

**Comment by scottcalebc** [comment]
Can leave in the java library date adjustment calls 👍

**Comment by scottcalebc** [comment]
Must include commits that ensure Dates work as character strings for string ops, i.e. for char in string loops, LEN, spaces, string indexing

**Comment by scottcalebc** [comment]
Date runs with updated p5Date.txt file

**Review by seco-dev — APPROVED** [review]

**Pull request merged**
